Upate David's git scripts.

diff --git a/script/git-all b/script/git-all
--- a/script/git-all
+++ b/script/git-all
@@ -1,35 +1,146 @@
-#! /bin/bash
+#!/bin/bash
+#
+# Run Git commands on each repository in the current directory.
+# Source: http://github.com/falconindy/bin-scripts/blob/master/git-all
+#
+REPOHOME=${REPOHOME:-$HOME}
+FORCE=0
+VERBOSE=0
 
-if [ ! "$1" == "push" ] && [ ! "$1" == "pull" ]; then
-	echo "git-all will push or pull all git repositories found one level deeper than your current location."
-	echo "USAGE: git-all push|pull [origin <remote>]"
-	exit
-fi
+count=0
+declare -a fail
+declare -a pass
+declare -A output
 
-FOUND=0
-SUCCESS=0
-FAIL=0
+usage() {
+  echo "Usage: ${0##*/} [options] [command]"
+  echo
+  echo "   -S    Show repos which have uncommitted changes. If this"
+  echo "          option is specified, all other options are ignored."
+  echo
+  echo "   -f    suppress prompting before a custom command is run"
+  echo "   -h    print this help message"
+  echo "   -v    print error output in job summary for failed jobs"
+  echo
+  echo " Actions will be performed on \$REPOHOME, which defaults to \$HOME"
+  echo " if not specified."
+  echo
 
-BASEDIR=`pwd`
+  exit 1
+} >&2
 
-for d in `find . -maxdepth 1 -type d`; do
-	d=`echo $d | sed -e 's/\.\///g'`
-	if [ -d ${BASEDIR}/${d}/.git ]; then
-		FOUND=$(($FOUND + 1))
-		cd ${BASEDIR}/${d}
-		git $1 $2 $3
+die() {
+  local mesg=$1; shift
+  printf "\033[1;31m::\033[0m ${mesg}\n" "$@" >&2
+}
 
-		if [ $? -eq 0 ]; then
-			SUCCESS=$(($SUCCESS + 1))
-		else
-			FAIL=$(($FAIL + 1))
-			echo "git-all: Error while ${1}ing repo `pwd`"
-		fi
-		echo ""
-	fi
+msg() {
+  local mesg=$1; shift
+  printf " \033[1;32m==>\033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >&2
+}
+
+msg2() {
+  local mesg=$1; shift
+  printf " \033[1;34m  ->\033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >&2
+}
+
+repopass() {
+  printf " \033[1;0m\033[0;34m[\033[1;37mPASS\033[0;34m] \033[0;36m %s\033[0m\n" "$1"
+}
+
+repofail() {
+  printf " \033[1;0m\033[0;34m[\033[1;31mFAIL\033[0;34m] \033[0;36m %s\033[0m\n" "$1" >&2
+}
+
+verify_execute() {
+  msg "Command to be executed: $*"
+  echo -ne "\033[1;33m::\033[0m"
+  read -N1 -p " Are you sure you want to do this? [y/N] " reply
+  echo
+
+  [[ ! "$reply" =~ [Yy] ]] && die "Operation aborted" && exit 1
+}
+
+validate_command() {
+  type -P $1 &> /dev/null || {
+    die "Invalid command: '$1'";
+    exit 1;
+  }
+}
+
+do_all_action() {
+  IFS=$'\n' read -r -d $'\0' -a repos < <(find "$REPOHOME" -type d -name '.git' -exec readlink -f {} \;)
+
+  for repo in "${repos[@]}"; do
+    (( ++count ))
+    local repo=${repo%.git}
+    cd "$repo"
+
+    output[$repo]=$("$@" 2>&1) &&
+      pass=(${pass[@]} "$repo") || fail=(${fail[@]} "$repo")
+
+  done
+}
+
+stat_repos() {
+  IFS=$'\n' read -r -d $'\0' -a repos < <(find "$REPOHOME" -type d -name '.git' -exec readlink -f {} \;)
+
+  for repo in "${repos[@]}"; do
+    local repo="${repo%.git}"
+    cd "$repo"
+    [[ -n $(git status -s | grep -v "^??") ]] && echo "$repo"
+  done
+
+  exit 0
+}
+
+job_summary() {
+  echo
+  msg "Job Summary For $count Repos: $*"
+
+  if [[ ${#fail[@]} -eq 0 ]]; then
+    msg2 "No errors were reported"
+  else
+    for repo in "${fail[@]}"; do
+      repofail "$repo"
+      { (( VERBOSE )) && sed 's/^/   /' <<< "${output[$repo]}" && echo; } >&2
+    done
+  fi
+  echo
+
+  for repo in "${pass[@]}"; do
+    repopass "$repo"
+  done
+  echo
+}
+
+[[ -z $1 ]] && usage
+
+[[ ! -d "$REPOHOME" ]] && die "Invalid directory specified for \$REPOHOME" exit 1
+
+while getopts :Shfv flag; do
+  case $flag in
+    S) stat_repos
+      ;;
+    h) usage
+      ;;
+    f) FORCE=1
+      ;;
+    v) VERBOSE=1
+      ;;
+    \?) die "invalid option -- '$OPTARG'"
+      usage
+      ;;
+  esac >&2
 done
 
-echo "git-all-${1}: $FOUND repositories found. $SUCCESS repositories affected."
-if [ $FAIL -gt 0 ]; then
-	echo "git-all-${1}: $FAIL errors occurred. Check console log for details."
-fi
+shift $(( OPTIND-1 ))
+
+# did user only provide flags?
+[[ -z $1 ]] && usage
+
+# meat
+(( FORCE )) || verify_execute "$*"
+validate_command "$1"
+do_all_action "$@"
+job_summary "$@"
diff --git a/script/git-retrotag b/script/git-retrotag
--- a/script/git-retrotag
+++ b/script/git-retrotag
@@ -3,64 +3,131 @@
 # Git retroactive auto-tagging script.
 # by Dave Reisner (d@falconindy.com)
 #
-commits=()
+declare -a commits
+declare -a existing_ags
 
-# parse git-whatchanged to earmark commits where VERSION was modified
-while read -r line; do
-  [[ $line =~ ^$ ]] && continue
-  if [[ ! $line =~ ^: ]]; then
-    # current commit being examined
-    read curcommit <<< $line
-    continue
+die() {
+  local mesg=$1; shift
+  printf "\033[1;31m::\033[0m ${mesg}\n" "$@" >&2
+}
+
+warn() {
+  local mesg=$1; shift
+  printf "\033[1;33m::\033[0m ${mesg}\n" "$@" >&2
+}
+
+info() {
+  local mesg=$1; shift
+  printf " \033[1;34m::\033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@"
+}
+
+msg() {
+  local mesg=$1; shift
+  printf " \033[1;32m==>\033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@"
+}
+
+in_array() {
+  local item needle=$1; shift
+  [[ -z "$1" ]] && return 1 # Not Found
+  for item; do
+    [[ $item = "$needle" ]] && return 0 # Found
+  done
+  return 1 # Not Found
+}
+
+check_repo_sanity() {
+  if ! git rev-parse --quiet --verify HEAD &>/dev/null; then
+    die "error: Not in a git repo"
+    exit 1
   fi
-
-  # parse file change information
-  read -r _ _ _ _ action file <<< $line
-  if [[ $action =~ [AM] && $file == "VERSION" ]]; then
-    commits+=("$curcommit")
+  if ! git diff-index --quiet HEAD; then
+    die "error: repo is dirty. Please commit or stash your changes before running this script."
+    exit 1
   fi
-done < <(git whatchanged --format="%H %ai")
-# create our own format so that we get the author date (we'll want it for tagging)
+}
 
-if (( ${#commits[@]} == 0 )); then
-  echo "error: No candidate commits were found for tagging" >&2
-  exit 1
-fi
+find_taggable_commits() {
+  local commit action file
 
-# step through the found commits for reassurance
-echo "Found ${#commits[@]} commits worthy of tagging. Press enter to review the commits."
-read
-for commit in "${commits[@]}"; do
-  read hash date <<< $commit
-  git show --stat $hash
-done
+  while read -r line; do
+    [[ $line =~ ^$ ]] && continue
+    if [[ ! $line =~ ^: ]]; then
+      # current commit being examined
+      read commit <<< $line
+      continue
+    fi
 
+    # parse file change information
+    read -r _ _ _ _ action file <<< $line
+    if [[ $action =~ [AM] && $file == "VERSION" ]]; then
+      commits+=("$commit")
+    fi
+  done < <(git whatchanged --format="%H %ai")
 
-# this is your chance to abort
-read -N1 -p "Satisfied? Continue with tagging? (y/N) " reply
-echo
-[[ ! "$reply" =~ [Yy] ]] && { echo "Aborting..."; exit 1; }
+  if (( ${#commits[@]} == 0 )); then
+    die "error: No candidate commits were found for tagging" >&2
+    exit 1
+  fi
+}
 
+get_existing_tags() {
+  IFS=$'\n' read -r -d'\0' -a existing_tags < <(git tag)
+}
 
-# do it!
-for commit in "${commits[@]}"; do
-  read hash date <<< $commit
-  [[ -z $hash || -z $date ]] && { echo "Fatal error! Something is horribly wrong" >&2; exit 42; }
-  {
+review_commits() {
+  msg "Found ${#commits[@]} commits worthy of tagging. Press enter to review the commits."
+  read
+  for commit in "${commits[@]}"; do
+    read hash date <<< $commit
+    git show --stat $hash
+  done
+}
+
+ask_abort() {
+  read -N1 -p "Satisfied? Continue with tagging? (y/N) " reply
+  echo
+  [[ ! "$reply" =~ [Yy] ]] && { echo "Aborting..."; exit 1; }
+}
+
+tag_commits() {
+  local count=0
+
+  for commit in "${commits[@]}"; do
+    read hash date <<< $commit
+    [[ -z $hash || -z $date ]] && { die "Fatal error! Something is horribly wrong!"; exit 42; }
+
     # make a new branch, rewound to the commit
-    git checkout $hash -b $hash
+    git checkout $hash -b $hash &>/dev/null
+
     version=$(< VERSION)
 
-    # embed the author date in the tag ref, as if it was tagged on the day of the commit
-    GIT_COMMITTER_DATE="$date" git tag -a "$version" -m "tag as $version"
+    # if the tag exists, skip tagging
+    if in_array $version "${existing_tags[@]}"; then
+      warn "Tag \"$version\" already exists. Skipping..."
+    else
+      GIT_COMMITTER_DATE="$date" git tag -a "$version" -m "tag as $version" &>/dev/null
+      info "${hash:0:8} => $version"
+      (( ++count ))
+    fi
 
     # reset for next iteration
-    git checkout master
-    git branch -d $hash
-  } &>/dev/null
-  echo "${hash:0:8} => $version"
-  unset hash date
-done
+    { git checkout master; git branch -d $hash; } &>/dev/null
+    unset hash date
+  done
 
-echo
-echo "Finished tagging! Use \`git push --tags\` to push all tag refs to the remote."
+  if (( count > 0 )); then
+    echo
+    msg "Finished: Added $count new tags. Use \`git push --tags\` to update the remote."
+  else
+    echo
+    msg "Finished: No new tags were added."
+  fi
+}
+
+# main loop
+check_repo_sanity
+find_taggable_commits
+get_existing_tags
+review_commits
+ask_abort
+tag_commits
